// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkuj3oedePBpC5R1Oc_sa_uk9u95mu6OA',
    appId: '1:591568493494:web:e0ef6d96f6fc53b7943f17',
    messagingSenderId: '591568493494',
    projectId: 'varateblog-bf4ae',
    authDomain: 'varateblog-bf4ae.firebaseapp.com',
    storageBucket: 'varateblog-bf4ae.appspot.com',
    measurementId: 'G-SPL2HXT3E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgR0yU79ac3vS0wLtL0UsLcmfl6RjlFXM',
    appId: '1:591568493494:android:c9f3ea2faa4a5ed3943f17',
    messagingSenderId: '591568493494',
    projectId: 'varateblog-bf4ae',
    storageBucket: 'varateblog-bf4ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuzwDYrvBB1vxKXS-LgPLaaD-WzAVBqj4',
    appId: '1:591568493494:ios:e416afb9f2a03807943f17',
    messagingSenderId: '591568493494',
    projectId: 'varateblog-bf4ae',
    storageBucket: 'varateblog-bf4ae.appspot.com',
    iosBundleId: 'com.example.adminWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuzwDYrvBB1vxKXS-LgPLaaD-WzAVBqj4',
    appId: '1:591568493494:ios:ae41688e7c9961e1943f17',
    messagingSenderId: '591568493494',
    projectId: 'varateblog-bf4ae',
    storageBucket: 'varateblog-bf4ae.appspot.com',
    iosBundleId: 'com.example.adminWebapp.RunnerTests',
  );
}
